# Generated by Django 3.1.2 on 2021-10-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20211027_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
